---

- name: APT | Install packages
  apt:
    name:
      - lvm2
      - scsitools
      - xfsprogs
    update_cache: true
    cache_valid_time: 3600
    state: present

- name: COMMAND | Checking for scsi devices
  command: sg_scan
  register: scsi_devices
  changed_when: false

- name: COMMAND | Rescanning for new disks added
  command: /usr/bin/rescan-scsi-bus.sh -a
  changed_when: false
  when:
    - scsi_devices.stdout is defined
    - scsi_devices.stdout != ""
