---

- name: Unmount mount point
  ansible.builtin.command: "umount /dev/{{ volume_group.vgname }}/{{ logical_volume.lvname }}"
  loop: "{{ volume_group.lvnames }}"
  loop_control:
    loop_var: logical_volume
  when: '"g" in logical_volume.size'
  ignore_errors: true

- name: Check for errors
  ansible.builtin.command: "e2fsck -fy /dev/{{ volume_group.vgname }}/{{ logical_volume.lvname }}"
  loop: "{{ volume_group.lvnames }}"
  loop_control:
    loop_var: logical_volume
  when: '"g" in logical_volume.size'
  ignore_errors: true

- name: Resize filesystem
  ansible.builtin.command: "resize2fs /dev/{{ volume_group.vgname }}/{{ logical_volume.lvname }} {{ logical_volume.size | upper }}"
  loop: "{{ volume_group.lvnames }}"
  loop_control:
    loop_var: logical_volume
  when: '"g" in logical_volume.size'
