---

- name: INCLUDE | Debian family
  ansible.builtin.include_tasks:
    file: "debian.yml"
  when: ansible_os_family == "Debian"

- name: INCLUDE | RedHat family
  ansible.builtin.include_tasks:
    file: "centos.yml"
  when: ansible_os_family == "RedHat"

- name: INCLUDE | Resize filesystems
  ansible.builtin.include_tasks:
    file: "volume_groups.yml"
  when: lvm_apply

- name: INCLUDE | Apply
  ansible.builtin.include_tasks:
    file: "manage_lvm.yml"
  when: lvm_apply